# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ‘playtext’ do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
pod 'AFNetworking'
pod 'Masonry'
pod 'WebViewJavascriptBridge'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDWebImage'
pod 'FMDB'
pod 'HyphenateLite'


  # Pods for SmallLoan

end
